language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - 2.1.2
script: 'rake spec'
env:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="3"
matrix:
    exclude:
        - rvm: 2.1.2
        - env: PUPPET_VERSION="~> 2.7.0"
gemfile: .gemfile
notifications:
    email: false
